config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tests do
    get :start, on: :member
    put :answer, on: :member

    get :reset, on: :collection
    post :reset, on: :collection
  end

  resources :questions do
    get :dashboard, on: :collection
  end
  resources :sessions
  resources :categories
  resources :answers

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'tests#index'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :category
  has_many :choices
  has_many :answers

  belongs_to :user
  belongs_to :confirmed_user, class_name: 'User', foreign_key: :confirmed_by, optional: true

  has_many :question_positions
  has_many :positions, through: :question_positions

  has_rich_text :title
  enum status: %i[active confirmed]

  accepts_nested_attributes_for :choices, allow_destroy: true, reject_if: :choice_rejectable?
  accepts_nested_attributes_for :positions

  private

  def choice_rejectable?(attrs)
    attrs['title'].blank?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :moderator_required

  # GET /questions
  # GET /questions.json
  def index
    @filter = QuestionSearch.new(filter_params)
    @questions = @filter.result.page(params[:page] || 0)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    if (last = Question.where(user: current_user).last)
      @question.position_ids = last.position_ids
    end
    4.times { @question.choices.build }
  end

  # GET /questions/1/edit
  def edit
    (4 - @question.choices.count).times { @question.choices.build }
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    expires_in 5.minutes
    @positions = Hr::Position.active
    @categories = Category.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.fetch(:question, {}).permit(:title, :category_id, :status, :source, :multiple, choices_attributes: %i[id title correct _destroy], position_ids: [])
  end

  def filter_params
    if current_user.admin?
      params.fetch(:search, {}).permit(:title, :status, :category, :user, :position, :multiple)
    else
      params.fetch(:search, {}).permit(:title, :status, :category, :position, :user, :multiple).merge(user: current_user)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= simple_form_for(@question) do |f|
  .mdc-layout-grid__inner
    .mdc-layout-grid__cell--span-7
      .mdc-card
        .crm-card--header
          .mdc-typography--headline6 Асуулт
          - unless @question.new_record?
            .mdc-button.mdc-button--raised data-mdc-auto-init='ripple'
              i.mdc-button__icon.material-icons person_add
              .mdc-button__label = @question.user.name
        .crm-card--content
          =f.error_notification

          .crm-form--row
            =f.input :category_id, icon: :category, collection: Category.active, as: :enhanced_select
          .crm-form--row
            =f.rich_text_area :title
          .crm-form--row
            =f.input :source, icon: :zoom_in
          .crm-form--row
            =f.input :status, icon: :check, collection: Question.statuses.map(&:first), as: :enhanced_select, disabled: true
      .mdc-card.mt2
        .crm-card--header
          .mdc-typography--headline6 Хариултууд
        .mdc-list.mdc-list--two-line.pa0
          =f.fields_for :choices do |b|
            .mdc-list-item
              =b.input :title, icon: 'check_circle', input_html: {class: 'w-420'}
              .mdc-list-item__meta
                =b.label :correct, class: 'mr3'
                =b.input :correct
              .mdc-list-item__meta
                =b.label :_destroy, 'Устгах', class: 'mr2'
                =b.input :_destroy, as: :boolean
            .mdc-list-divider
        .crm-card--footer
          = f.button :submit, 'Хадгалах'
          = link_to :back, class: 'mdc-button ml3', data: {'mdc-auto-init' => 'ripple'} do
            i.material-icons.mdc-button__icon arrow_back
            .mdc-button__label Буцах

    .mdc-layout-grid__cell--span-5
      .mdc-card.h100
        .crm-card--header
          =f.label :multiple, class: 'mdc-typography--headline6 tu'
          =f.input :multiple
        .crm-card--content.h100.scrollable
          .scrollable-content
            = f.collection_check_boxes :position_ids, Hr::Position.active.order(emp_count: :desc, name: :asc), :id, :title, include_hidden: false do |cb|
              .mdc-form-field.w-100
                .mdc-checkbox
                  = cb.check_box class: 'mdc-checkbox__native-control'
                  .mdc-checkbox__background
                    svg.mdc-checkbox__checkmark viewBox='0 0 24 24'
                      path.mdc-checkbox__checkmark-path fill='none' d='M1.73,12.91 8.1,19.28 22.79,4.59'
                    .mdc-checkbox__mixedmark
                = cb.label

app/views/questions/dashboard.html.slim
- content_for :page_title
  i.material-icons.pr2 help
  .mdc-typography--headline6 Асуултын нэгтгэл
.crm-page__main.mdc-layout-grid
  .mdc-layout-grid__inner
    .mdc-layout-grid__cell--span-12
      .mdc-card
        .mdc-data-table
          table.mdc-data-table__table.overflow-hidden 
            thead
              tr.mdc-data-table__header-row
                th.w-200.mdc-data-table__header-cell.b-r1 Албан тушаал
                - @categories.each do |category|
                  th.mdc-data-table__header-cell.rotated.bb1
                    div
                      span=category.name
            tbody.mdc-data-table__content
              - @positions.each do |pos|
                tr.mdc-data-table__row style='height: 28px;'
                  td.mdc-data-table__cell.b-r1
                    .mdc-typography--caption=pos.title
                  - @categories.each do |category|
                    td.b-r1.mdc-data-table__cell.tc
                      .mdc-typography--caption=category.position_questions(pos).size

app/views/questions/edit.html.slim
-content_for :page_title 
  i.material-icons.pr2 edit
  .mdc-typography--headline6 Асуулт засварлах

.crm-page__main.mdc-layout-grid
  == render 'form'

app/views/questions/index.html.slim
- content_for :page_title
  i.material-icons.pr2 help
  .mdc-typography--headline6 Асуултууд
.crm-page__main.mdc-layout-grid
  .mdc-layout-grid__inner
    .mdc-layout-grid__cell--span-9
      .mdc-card
        .mdc-data-table
          table.mdc-data-table__table
            thead
              tr.mdc-data-table__header-row
                th.mdc-data-table__header-cell #
                th.mdc-data-table__header-cell Төрөл
                th.mdc-data-table__header-cell Асуулт
                th.mdc-data-table__header-cell Зохиосон
                th.mdc-data-table__header-cell Сонгогдсон
                th.mdc-data-table__header-cell Зөв хариулт
                th.mdc-data-table__header-cell
                
            tbody.mdc-data-table__content
              - @questions.each do |question|
                tr.mdc-data-table__row
                  td.mdc-data-table__cell = link_to question.id, question, class: 'text-primary'
                  td.mdc-data-table__cell = question.category.title
                  td.mdc-data-table__cell = truncate(strip_tags(question.title.to_s), length: 50)
                  td.mdc-data-table__cell = question.user.name
                  td.mdc-data-table__cell = question.answers.count
                  td.mdc-data-table__cell = question.answers.where(correct: true).count
                  td.mdc-data-table__cell.pa0
                    = link_to 'edit', edit_question_path(question), class: 'mdc-icon-button material-icons', data: {'tippy-content': 'Засварлах'}
                    = link_to 'clear', question, data: { confirm: 'Мэдээллийг үнэхээр устгах уу?' }, method: :delete, class: 'mdc-icon-button material-icons'
          ==render partial: 'kaminari/pagination', locals: {list: @questions}
    .mdc-layout-grid__cell--span-3
      .mdc-card
        .crm-card--header
          .mdc-typography--headline6 Хайлт
        .crm-card--content
           =simple_form_for(@filter, as: :search, url: questions_path, method: :get) do |f|
            .crm-form--row
              =f.input :title, icon: :edit
            .crm-form--row
              =f.input :category, icon: :filter_list, collection: Category.all, as: :enhanced_select
            .crm-form--row
              =f.input :status, collection: Question.statuses.map(&:first)
            .crm-form--row
              =f.input :user, icon: :person_add, collection: User.where(id: Question.group(:user_id).pluck(:user_id)), disabled: !current_user.admin? 
            .crm-form--row
              =f.input :position, icon: :group, collection: Hr::Position.all.map {|p| [p.title, p.id]} 
            .crm-form-field.mt2.flex.justify-between.items-center
              =f.label :multiple, class: 'mdc-typography--button'
              =f.input :multiple, as: :boolean
            .mt3.flex.justify-between
            
              button.mdc-button.mdc-button--raised type='submit'
                i.material-icons.mdc-button__icon search
                .mdc-button__label Хайх
      a.mdc-button.mdc-button--outlined.mt3.w-100 href=dashboard_questions_path data-mdc-auto-init='ripple'
        i.material-icons.mdc-button__icon menu_open
        .mdc-button__label Нэгтгэл харах
  a.mdc-fab.mdc-fab--fixed href=new_question_path data-tippy-content='Асуулт нэмэх'
    .mdc-fab__icon.material-icons add

app/views/questions/new.html.slim
-content_for :page_title 
  i.material-icons.pr2 add
  .mdc-typography--headline6 Асуулт үүсгэх

.crm-page__main.mdc-layout-grid
  == render 'form'

app/views/questions/show.html.slim
- content_for :page_title
  .mdc-typography--headline6
    | Асуулт #
    =@question.id
.crm-page__main.mdc-layout-grid
  .mdc-layout-grid__inner
    .mdc-layout-grid__cell--span-9
      .mdc-card
        .mdc-typography--body1.pa3
          ==@question.title
        ul.mdc-list.pa0 role='radiogroup'
          - @question.choices.each_with_index do |choice, idx|
            .mdc-list-divider
            li.mdc-list-item role='radio' data-mdc-auto-init='ripple'
              span.mdc-list-item__graphic
                span.ml4 =%w[A B C D].fetch(idx)
                .mdc-radio
                  input.mdc-radio__native-control type='radio'
                  .mdc-radio__background
                    .mdc-radio__outer-circle
                    .mdc-radio__inner-circle
              label.mdc-list-item__text.word-wrap for="answer_choice_id_#{choice.id}"
                =choice.title
      .flex.justify-around.mt4
        a.mdc-button.mdc-button--raised href=new_question_path data-mdc-auto-init='ripple'
          i.material-icons.mdc-button__icon add
          .mdc-button__label Шинэ асуулт
        a.mdc-button.mdc-button--raised href=edit_question_path(@question) data-mdc-auto-init='ripple'
          i.material-icons.mdc-button__icon edit
          .mdc-button__label Асуултыг засах
      .mdc-card.mt3
        .crm-card--header
          .mdc-typography--headline6.tu Хариулууд
        .mdc-list.mdc-list--two-line
          -@question.answers.each do |answer|
            .mdc-list-item
              i.mdc-list-item__graphic.material-icons class=(answer.correct ? 'text-success' : 'text-danger')
                =(answer.correct ? 'check' : 'clear')
              .mdc-list-item__text
                .mdc-list-item__primary-text=answer.user.name
                .mdc-list-item__secondary-text=answer.choice.title.truncate(150) if answer.choice.present?
              .mdc-list-item__meta=answer.user.employee.position.name
            .mdc-list-divider



    .mdc-layout-grid__cell--span-3
      .mdc-card
        .crm-card--header
          i.material-icons settings
          .mdc-typography--headline6.tu Тохиргоо
        .crm-card--content
          dl.mt16
            dt Бүх хүмүүсээс авах эсэх
            dd=@question.multiple
          .mdc-typography--body1.text-primary Албан тушаал
          .mdc-chip-set
            - @question.positions.each do |pos|
              .mdc-chip data-mdc-auto-init='ripple'
                .mdc-chip__text=pos.title