config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tests do
    get :start, on: :member
    put :answer, on: :member

    get :reset, on: :collection
    post :reset, on: :collection
  end

  resources :questions do
    get :dashboard, on: :collection
  end
  resources :sessions
  resources :categories
  resources :answers

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'tests#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :session
  belongs_to :choice, optional: true

  validates :user, uniqueness: { scope: %i[session question] }
  enum status: %i[pending correct incorrect]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    if @answer.session.eligible? && @answer.update(answer_params)
      render json: :success
    else
      render json: :error
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.fetch(:answer, {}).permit(:choice_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.slim
= simple_form_for(@answer) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs

  .form-actions
    = f.button :submit

app/views/answers/edit.html.slim
h1 Editing answer

== render 'form'

=> link_to 'Show', @answer
'|
=< link_to 'Back', answers_path

app/views/answers/index.html.slim
h1 Listing answers

table
  thead
    tr
      th
      th
      th

  tbody
    - @answers.each do |answer|
      tr
        td = link_to 'Show', answer
        td = link_to 'Edit', edit_answer_path(answer)
        td = link_to 'Destroy', answer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.slim
h1 New answer

== render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_answer_path(@answer)
'|
=< link_to 'Back', answers_path