config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tests do
    get :start, on: :member
    put :answer, on: :member

    get :reset, on: :collection
    post :reset, on: :collection
  end

  resources :questions do
    get :dashboard, on: :collection
  end
  resources :sessions
  resources :categories
  resources :answers

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'tests#index'
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :test_categories
  has_many :test, through: :test
  has_many :questions
  enum status: %i[active inactive]

  def name
    title
  end

  def user_questions(user)
    assigned = questions.where(multiple: false)
                        .includes(:positions)
                        .where('hr_positions.id = ?', user.employee.position.id)
                        .pluck(:id)
                        .uniq

    (assigned + public_questions).uniq
  end

  def position_questions(position)
    assigned = questions.where(multiple: false)
                        .includes(:positions)
                        .where('hr_positions.id = ?', position.id)
                        .pluck(:id)
                        .uniq

    (assigned + public_questions).uniq
  end

  def public_questions
    questions.where(multiple: true).pluck(:id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.fetch(:category, {}).permit(:title, :score, :status)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  .mdc-layout-grid__inner
    .mdc-layout-grid__cell--span-6
      .mdc-card
        .crm-card--content
          = f.error_notification
          .crm-form--row
            =f.input :title, icon: :edit
          .crm-form--row
            =f.input :score, icon: :mood
          .crm-form--row
            =f.input :status, icon: :check, collection: Category.statuses.map(&:first)
        .crm-card--footer
          = f.button :submit

app/views/categories/edit.html.slim
-content_for :page_title
  i.material-icons.pr2 add
  .mdc-typography--headline6 Асуултын төрөл

.crm-page__main.mdc-layout-grid
  == render 'form'

app/views/categories/index.html.slim
- content_for :page_title
  i.material-icons.pr2 filter_list
  .mdc-typography--headline6 Асуултын төрөл
.crm-page__main.mdc-layout-grid
  .mdc-layout-grid__inner
    .mdc-layout-grid__cell--span-9
      .mdc-card
        .mdc-data-table
          table.mdc-data-table__table
            tr.mdc-data-table__header-row
              th.mdc-data-table__header-cell #
              th.mdc-data-table__header-cell Төрөл
              th.mdc-data-table__header-cell Оноо
              th.mdc-data-table__header-cell Асуулт
              th.mdc-data-table__header-cell Төлөв
              th.mdc-data-table__header-cell
            tbody.mdc-data-table__content
              - @categories.each do |category|
                tr.mdc-data-table__row
                  td.mdc-data-table__cell = category.id
                  td.mdc-data-table__cell = category.title
                  td.mdc-data-table__cell = category.score
                  td.mdc-data-table__cell = category.questions.count
                  td.mdc-data-table__cell = category.status
                  td.mdc-data-table__cell.pa0
                    = link_to 'edit', edit_category_path(category), class: 'mdc-icon-button material-icons', data: {'tippy-content': 'Засварлах'}
                    = link_to 'clear', category, data: { confirm: 'Мэдээллийг үнэхээр устгах уу?' }, method: :delete, class: 'mdc-icon-button material-icons'
  = link_to new_category_path, class: 'mdc-fab mdc-fab--fixed'
    i.material-icons.mdc-fab__icon add

app/views/categories/new.html.slim
-content_for :page_title
  i.material-icons.pr2 add
  .mdc-typography--headline6 Асуултын төрөл үүсгэх

.crm-page__main.mdc-layout-grid
  == render 'form'

app/views/categories/show.html.slim
-content_for :page_title
  i.material-icons.pr3 filter_list
  .mdc-typography--headline6=@category.title
.crm-page__main.mdc-layout-grid
  .mdc-layout-grid__inner
    .mdc-layout-grid__cell--span-3
      .mdc-card
        .crm-card--content
          dl
            dt Оноо
            dd =@category.score
            dt Төлөв
            dd =@category.status
  .mdc-layout-grid__cell--span-3
    .mdc-card
      